### ISSUE TITLE
What is the config of FLUX? 

### ISSUE THREAD

**Issue by Wangmmx** [zelcash/zelflux#280]
Is pubKeyHash the same as Zelcash?

There are ZEN and ZEL configurations in the project, whose pubkeyHash are 2089 and 1cb8. Which one should I use? Or neither of them is right?

**Comment by TheTrunk** [comment]
Yes follow configuration of zelcash. Flux has recently rebranded from zelcash and thus in many references you will still find it. Where do you see configuration for ZEN? As we do not have any connections to that project (apart from it being an asset present in zelcore platform, so that is where some configuration of that coin is surely present)

**Comment by Wangmmx** [comment]
So the pubKeyHash is 1cb8, and the scriptHash is 1cbd?

**Comment by TheTrunk** [comment]
zeltrezjs is a very old repository used in zelcore project and thus it has zen configuration
zelcashjs is deprecated as well.
The best source to look at current coins configuration that are in zelcore is this file:
https://github.com/ZelCore-io/Zelcore/blob/master/coinsSimple.js#L10

Flux has
```
    pubKeyHash: "1cb8",
    scriptHash: "1cbd",
```

You can also find it directly in flux source here:
https://github.com/RunOnFlux/fluxd/blob/master/src/chainparams.cpp#L177

**Comment by Wangmmx** [comment]
Ok thanks for your reply! It helped a lot
